version: "3.7"
services:
  wikigold:
    build: .
    environment:
      - FLASK_APP=wikigold
      - FLASK_ENV=development
      - SECRET_KEY=dev
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=wikigold
      - PREFIX=/wikigold
    ports:
      - "8000:8000"
    volumes:
      - /home/szyolewn/wikigold_data:/root/wikigold_data

  db:
    image: mariadb:10.6.2
    command: mysqld --innodb-buffer-pool-size=8589934592 # 8GiB
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    volumes:
      - /home/szyolewn/wikigold_dbdata:/var/lib/mysql

  redis:
    image: redis:6.2.6
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /home/szyolewn/wikigold_redis-data:/data
      - /home/szyolewn/wikigold_redis-conf:/usr/local/etc/redis

  adminer:
    image: adminer
    ports:
      - "8080:8080"

