version: "3.7"
services:
  wikigold:
    image: kask.eti.pg.edu.pl:5001/szyolewn/wikigold:latest
    restart: always
    environment:
      - FLASK_APP=wikigold
      - FLASK_ENV=production
      - SECRET_KEY=changeme  # change to: openssl rand -base64 16
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=changeme  # change to: openssl rand -base64 16
      - MYSQL_DATABASE=wikigold
      - REDIS_URL=redis://redis:6379
      - BASEURL=http://localhost
      - PREFIX=/wikigold  # the path to application (must be the same as in proxy server)
      - KNOWLEDGE_BASE=1
      - TOKENS_LIMIT=2000
    ports:
      - "8000:8000"

  db:
    image: mariadb:10.6.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme  # the same as above
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.6
    restart: always
    command: redis-server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data

volumes:
  dbdata:
  redis-data: