version: "3.7"
services:
  flask:
    image: https://kask.eti.pg.edu.pl/gitlab/szyolewn/wikigold/container_registry/
    restart: always
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=wikigold
      - PREFIX=/wikigold

  db:
    image: mariadb:10.6.2
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
