version: "3.7"
services:
  wikigold:
    build: .
    environment:
      - FLASK_APP=wikigold
      - FLASK_ENV=development
      - SECRET_KEY=dev
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=wikigold
      - REDIS_URL=redis://redis:6379
      - PREFIX=/wikigold
      - KNOWLEDGE_BASE=1
    ports:
      - "8000:8000"
    volumes:
      - /home/szyolewn/wikigold_data:/root/wikigold_data

  db:
    image: mariadb:10.6.2
    # command: mysqld --innodb-buffer-pool-size=8589934592 # 8GiB - for dump import only
    command: mysqld --max-allowed-packet=4096M
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    volumes:
      - /home/szyolewn/wikigold_dbdata:/var/lib/mysql

  redis:
    image: redis:6.2.6
    command: redis-server #/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  redis-data: