version: "3.7"
services:
  flask:
    build: ./flask
    container_name: flask
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=wikigold
      - BASEURL=http://localhost
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80

  db:
    image: mariadb:10.6.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
