version: "3.7"
services:
  flask:
    build: .
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - SECRET_KEY=dev
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=wikigold
      - PREFIX=/wikigold
    ports:
      - 8000:8000

  db:
    image: mariadb:10.6.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080
